# 分词池袋模型

In [ ]:
!pip install sklearn


In [18]:
import numpy as np 
sentence="Life is like music. It must be composed by ear, feeling and instinct, not by rule."
token=sentence.split()
vocad=sorted(set(token))# 对英文文本进行排序，数字最先，大写在前，小写在后
 
','.join(vocad)
print(token)
print(vocad)
num_tokens=len(token)
vocad_size=len(vocad)
#print(num_tokens)
#print(vocad_size)
onehot_vec=np.zeros((num_tokens,vocad_size),int)
print(onehot_vec)
for i, word in enumerate(token):
        onehot_vec[i,vocad.index(word)]=1
        
print(onehot_vec)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)


['Life', 'is', 'like', 'music.', 'It', 'must', 'be', 'composed', 'by', 'ear,', 'feeling', 'and', 'instinct,', 'not', 'by', 'rule.']
['It', 'Life', 'and', 'be', 'by', 'composed', 'ear,', 'feeling', 'instinct,', 'is', 'like', 'music.', 'must', 'not', 'rule.']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0

In [19]:
import pandas as pd 
df=pd.DataFrame(onehot_vec,columns=vocad)
print(df)

    It  Life  and  be  by  composed  ear,  feeling  instinct,  is  like  \
0    0     1    0   0   0         0     0        0          0   0     0   
1    0     0    0   0   0         0     0        0          0   1     0   
2    0     0    0   0   0         0     0        0          0   0     1   
3    0     0    0   0   0         0     0        0          0   0     0   
4    1     0    0   0   0         0     0        0          0   0     0   
5    0     0    0   0   0         0     0        0          0   0     0   
6    0     0    0   1   0         0     0        0          0   0     0   
7    0     0    0   0   0         1     0        0          0   0     0   
8    0     0    0   0   1         0     0        0          0   0     0   
9    0     0    0   0   0         0     1        0          0   0     0   
10   0     0    0   0   0         0     0        1          0   0     0   
11   0     0    1   0   0         0     0        0          0   0     0   
12   0     0    0   0   0

In [21]:
sentence_bow={}
for token in sentence.split():
    sentence_bow[token]=1
print(type(sentence_bow))
sorted(sentence_bow.items())

<class 'dict'>


[('It', 1),
 ('Life', 1),
 ('and', 1),
 ('be', 1),
 ('by', 1),
 ('composed', 1),
 ('ear,', 1),
 ('feeling', 1),
 ('instinct,', 1),
 ('is', 1),
 ('like', 1),
 ('music.', 1),
 ('must', 1),
 ('not', 1),
 ('rule.', 1)]

In [26]:
s=pd.Series(sentence_bow)
df2=pd.DataFrame(s,columns=["sent"])
df2=df2.T
print(df2)

      Life  is  like  music.  It  must  be  composed  by  ear,  feeling  and  \
sent     1   1     1       1   1     1   1         1   1     1        1    1   

      instinct,  not  rule.  
sent          1    1      1  


In [ ]:
sents="To be both a speaker of words and a doer of deeds.\n"
sents+="Only they who fulfill their duties in everyday matters will fulfill them on great occasions.\n"
sents+="The shortest way to do many things is to only one thing at a time. \n"
sents+="Life is like music. It must be composed by ear, feeling and instinct, not by rule.\n"
sents+="Life is a great big canvas, and you should throw all the paint on it you can."
