# 分词池袋模型

In [1]:
!pip install sklearn


  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=927d5bae6c48e40187db15761d28338364ecb892537f1262dd2a6e7aa8cc6211
  Stored in directory: c:\users\tomis\appdata\local\pip\cache\wheels\e4\7b\98\b6466d71b8d738a0c547008b9eb39bf8676d1ff6ca4b22af1c
Successfully built sklearn


# 自然语言处理pipeline


In [25]:
import numpy as np 
sentence="Life is like music. It must be composed by ear, feeling and instinct, not by rule."
token=sentence.split()
vocad=sorted(set(token))# 对英文文本进行排序，数字最先，大写在前，小写在后
 
','.join(vocad)
print(token)
print(vocad)
num_tokens=len(token)
vocad_size=len(vocad)
#print(num_tokens)
#print(vocad_size)
onehot_vec=np.zeros((num_tokens,vocad_size),int)
print(onehot_vec)
for i, word in enumerate(token):
        onehot_vec[i,vocad.index(word)]=1
        
print(onehot_vec)



['Life', 'is', 'like', 'music.', 'It', 'must', 'be', 'composed', 'by', 'ear,', 'feeling', 'and', 'instinct,', 'not', 'by', 'rule.']
['It', 'Life', 'and', 'be', 'by', 'composed', 'ear,', 'feeling', 'instinct,', 'is', 'like', 'music.', 'must', 'not', 'rule.']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0

In [5]:
import pandas as pd 
df=pd.DataFrame(onehot_vec,columns=vocad)
print(df)

    It  Life  and  be  by  composed  ear,  feeling  instinct,  is  like  \
0    0     1    0   0   0         0     0        0          0   0     0   
1    0     0    0   0   0         0     0        0          0   1     0   
2    0     0    0   0   0         0     0        0          0   0     1   
3    0     0    0   0   0         0     0        0          0   0     0   
4    1     0    0   0   0         0     0        0          0   0     0   
5    0     0    0   0   0         0     0        0          0   0     0   
6    0     0    0   1   0         0     0        0          0   0     0   
7    0     0    0   0   0         1     0        0          0   0     0   
8    0     0    0   0   1         0     0        0          0   0     0   
9    0     0    0   0   0         0     1        0          0   0     0   
10   0     0    0   0   0         0     0        1          0   0     0   
11   0     0    1   0   0         0     0        0          0   0     0   
12   0     0    0   0   0

In [6]:
sentence_bow={}
for token in sentence.split():
    sentence_bow[token]=1
print(type(sentence_bow))
sorted(sentence_bow.items())

<class 'dict'>


[('It', 1),
 ('Life', 1),
 ('and', 1),
 ('be', 1),
 ('by', 1),
 ('composed', 1),
 ('ear,', 1),
 ('feeling', 1),
 ('instinct,', 1),
 ('is', 1),
 ('like', 1),
 ('music.', 1),
 ('must', 1),
 ('not', 1),
 ('rule.', 1)]

In [7]:
s=pd.Series(sentence_bow)
df2=pd.DataFrame(s,columns=["sent"])
df2=df2.T
print(df2)

      Life  is  like  music.  It  must  be  composed  by  ear,  feeling  and  \
sent     1   1     1       1   1     1   1         1   1     1        1    1   

      instinct,  not  rule.  
sent          1    1      1  


In [12]:
sents="To be both a speaker of words and a doer of deeds.\n"
sents+="Only they who fulfill their duties in everyday matters will fulfill them on great occasions.\n"
sents+="The shortest way to do many things is to only one thing at a time. \n"
sents+="Life is like music. It must be composed by ear, feeling and instinct, not by rule.\n"
sents+="Life is a great big canvas, and you should throw all the paint on it you can."
print(sents)
corpus={}
for i,sent in enumerate(sents.split("\n")):
    corpus['sent{}'.format(i)]=dict((tok,1) for tok in sent.split())
df=pd.DataFrame.from_records(corpus).fillna(0).astype(int).T
df[df.columns[:20]]

To be both a speaker of words and a doer of deeds.
Only they who fulfill their duties in everyday matters will fulfill them on great occasions.
The shortest way to do many things is to only one thing at a time. 
Life is like music. It must be composed by ear, feeling and instinct, not by rule.
Life is a great big canvas, and you should throw all the paint on it you can.


To  be  both  a  speaker  of  words  and  doer  deeds.  Only  they  \
sent0   1   1     1  1        1   1      1    1     1       1     0     0   
sent1   0   0     0  0        0   0      0    0     0       0     1     1   
sent2   0   0     0  1        0   0      0    0     0       0     0     0   
sent3   0   1     0  0        0   0      0    1     0       0     0     0   
sent4   0   0     0  1        0   0      0    1     0       0     0     0   

       who  fulfill  their  duties  in  everyday  matters  will  
sent0    0        0      0       0   0         0        0     0  
sent1    1        1      1       1   1         1        1     1  
sent2    0        0      0       0   0         0        0     0  
sent3    0        0      0       0   0         0        0     0  
sent4    0        0      0       0   0         0        0     0

In [20]:
sent1_v=df.iloc[0,:].T
print(sent1_v)
sent2_v=df.iloc[1,:]
print(sent2_v)
sent1_v@sent2_v
sent3_v=df.iloc[3,:]
sent1_v@sent3_v

To            1
be            1
both          1
a             1
speaker       1
of            1
words         1
and           1
doer          1
deeds.        1
Only          0
they          0
who           0
fulfill       0
their         0
duties        0
in            0
everyday      0
matters       0
will          0
them          0
on            0
great         0
occasions.    0
The           0
shortest      0
way           0
to            0
do            0
many          0
things        0
is            0
only          0
one           0
thing         0
at            0
time.         0
Life          0
like          0
music.        0
It            0
must          0
composed      0
by            0
ear,          0
feeling       0
instinct,     0
not           0
rule.         0
big           0
canvas,       0
you           0
should        0
throw         0
all           0
the           0
paint         0
it            0
can.          0
Name: sent0, dtype: int32
To            0
be            

2

### n-gram
n-gram是一个最多包含n个元素的序列，这些元素从由他们组成的序列（通常是字符）中提取而成。

一般而言，n-gram的“元素”可以是字符，音节，词，甚至是“A”,"T","G","C"等DNA序列的符号

> NLP，n-gram即可由词构成例如“hello you” 为词的2-gram，“yo”为字母的2-gram。n-gram不一定要求像复合词一样具有特定含义，而仅仅要求出现频率足够高以引起词条计数器的注意。

In [21]:
!pip install nltk

In [28]:
from nltk.util import ngrams
list(ngrams(token,2))
 


[('Life', 'is'),
 ('is', 'like'),
 ('like', 'music.'),
 ('music.', 'It'),
 ('It', 'must'),
 ('must', 'be'),
 ('be', 'composed'),
 ('composed', 'by'),
 ('by', 'ear,'),
 ('ear,', 'feeling'),
 ('feeling', 'and'),
 ('and', 'instinct,'),
 ('instinct,', 'not'),
 ('not', 'by'),
 ('by', 'rule.')]