## 线性代数基础

### 对称矩阵

>如果一个矩阵 $S$ 的所有数据项都满足$S

## SVD 
https://zhuanlan.zhihu.com/p/29846048
> 优点：简化数据，去除噪声，提高算法的结果
> 
> 缺点：数据的转换可能难以理解
> 
> 适用数据范围：数值型数据
利用SVD实现，可以能够用小的多的数据来表示原始数据，如此，实际上是去除了噪声和多余信息。
---
结合特征分解知识

特征值的分解使用于

SVD是将任意复杂（注意对比特征分解只能适用于方阵）的矩阵用更小，更简单的3个矩阵的相乘表示，用这3个小矩阵来描述大矩阵的重要特征。

利用SVD 可以从稀疏矩阵（矩阵中有大量元素值为0）中提取有价值的信息，减少计算量，在使用线性代数的地方，基本上都要使用SVD。

SVD不但应用在PCA、图像压缩、数字水印、推荐系统和文章分类、LSA中，是很多机器学习算法基石。

### SVD数学定义
与特征值分解不同，SVD不要求原始矩阵为方阵。

In [2]:
!pip install numpy

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ---------------------------------------- 14.6/14.6 MB 9.5 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\tomis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy as np 
from numpy import linalg as la 
A=np.array([1,5,7,6,1,2,1,10,4,4, 3,6,7,5,2]).reshape(3,5)
print(A)


[[ 1  5  7  6  1]
 [ 2  1 10  4  4]
 [ 3  6  7  5  2]]


In [ ]:
!pip uninstall pyzmq