## 线性代数基础

### 对称矩阵

>如果一个矩阵 $S$ 的所有数据项都满足$S

## SVD (Singular Value Decomposition）奇异值分解
https://zhuanlan.zhihu.com/p/29846048
> 优点：简化数据，去除噪声，提高算法的结果
> 
> 缺点：数据的转换可能难以理解
> 
> 适用数据范围：数值型数据
利用SVD实现，可以能够用小的多的数据来表示原始数据，如此，实际上是去除了噪声和多余信息。
---
结合特征分解知识

特征值的分解使用于

SVD是将任意复杂（注意对比特征分解只能适用于方阵）的矩阵用更小，更简单的3个矩阵的相乘表示，用这3个小矩阵来描述大矩阵的重要特征。

利用SVD 可以从稀疏矩阵（矩阵中有大量元素值为0）中提取有价值的信息，减少计算量，在使用线性代数的地方，基本上都要使用SVD。

SVD不但应用在PCA、图像压缩、数字水印、推荐系统和文章分类、LSA中，是很多机器学习算法基石。

### SVD数学定义
与特征值分解不同，SVD不要求原始矩阵为方阵。

$$ A=U_{m \times m} \Sigma_{m \times n} V^T_{n \times n}$$
-------
 A 为$m \times n$矩阵，$A \times A^T$ 将得到一个对称矩阵，即$A_{ij}=A_{ji}$
*  $U$ 是一个$m \times m$的矩阵，
*  $ \Sigma$ 是一个 $m \times n$ 的矩阵，除了主对角线上的元素以外全为0，主对角线上的每个元素都称为奇异值。奇异值矩阵是一个对角矩阵，除了对角元素外其他元素都为0
*  $V$ 是一个 $n \times n$ 的矩阵。
*  
$U$和$V$ 都是酉矩阵，即满足
$U^T T=E_{m \times m} , V^TV=E_{n \times n}$

 ---

 

>SVD是对数据进行有效特征整理的过程。首先，对于一个m×n矩阵A，我们可以理解为其有m个数据，n个特征，（想象成一个n个特征组成的坐标系中的m个点），然而一般情况下，这n个特征并不是正交的，也就是说这n个特征并不能归纳这个数据集的特征。SVD的作用就相当于是一个坐标系变换的过程，从一个不标准的n维坐标系，转换为一个标准的k维坐标系，并且使这个数据集中的点，到这个新坐标系的欧式距离为最小值（也就是这些点在这个新坐标系中的投影方差最大化），其实就是一个最小二乘的过程。进一步，如何使数据在新坐标系中的投影最大化呢，那么我们就需要让这个新坐标系中的基尽可能的不相关，我们可以用协方差来衡量这种相关性。A^T·A中计算的便是n×n的协方差矩阵，每一个值代表着原来的n个特征之间的相关性。当对这个协方差矩阵进行特征分解之后，我们可以得到奇异值和右奇异矩阵，而这个右奇异矩阵则是一个新的坐标系，奇异值则对应这个新坐标系中每个基对于整体数据的影响大小，我们这时便可以提取奇异值最大的k个基，作为新的坐标，这便是PCA的原理。

通过python中np.linga.svd 求奇异分解
 Python中svd后得到的sigma是一个行向量，Python中为了节省空间只保留了A的奇异值，所以我们需要将它还原为奇异值矩阵。同时需要注意的是，比如一个5*5 大小的矩阵的奇异值只有两个，但是他的奇异值矩阵应该是 5*5的，所以后面的我们需要手动补零，并不能直接使用diag将sigma对角化。
————————————————
https://blog.csdn.net/Cheese_pop/article/details/78346662

t

In [18]:
import numpy as np 
from numpy import linalg as la 
A=np.array([1,5,7,6,1,2,1,10,4,4, 3,6,7,5,2]).reshape(3,5)
print("A与自身转置相乘，得到一个对称矩阵：",A@A.T,"得到对称矩阵形状：",(A@A.T).shape)
print("原始矩阵：",A,"原始矩阵形状:",A.shape)
print(A@A.T)
U,s,Vt=la.svd(A)
Sigma=np.zeros(A.shape)#首先得到一个m*n的空矩阵，作为奇异值矩阵
print("左奇异矩阵",U,"矩阵形状：",U.shape)
print("右奇异矩阵",Vt,"矩阵形状：",Vt.shape)
 
for i in range(len(s)):#为奇异值矩阵对角元素赋值
    Sigma[i,i]=s[i]
print("奇异值矩阵：",Sigma,"奇异值矩阵形状：",Sigma.shape)

A与自身转置相乘，得到一个对称矩阵： [[112 105 114]
 [105 137 110]
 [114 110 123]] 得到对称矩阵形状： (3, 3)
原始矩阵： [[ 1  5  7  6  1]
 [ 2  1 10  4  4]
 [ 3  6  7  5  2]] 原始矩阵形状: (3, 5)
[[112 105 114]
 [105 137 110]
 [114 110 123]]
左奇异矩阵 [[-0.55572489  0.40548161 -0.72577856]
 [-0.59283199 -0.80531618  0.00401031]
 [-0.58285511  0.43249337  0.68791671]] 矩阵形状： (3, 3)
右奇异矩阵 [[-0.18828164 -0.37055755 -0.74981208 -0.46504304 -0.22080294]
 [ 0.01844501  0.76254787 -0.4369731   0.27450785 -0.38971845]
 [ 0.73354812  0.27392013 -0.12258381 -0.48996859  0.36301365]
 [ 0.36052404 -0.34595041 -0.43411102  0.6833004   0.30820273]
 [-0.5441869   0.2940985  -0.20822387 -0.0375734   0.7567019 ]] 矩阵形状： (5, 5)
奇异值矩阵： [[18.53581747  0.          0.          0.          0.        ]
 [ 0.          5.0056557   0.          0.          0.        ]
 [ 0.          0.          1.83490648  0.          0.        ]] 奇异值矩阵形状： (3, 5)


In [22]:
B=U@Sigma@Vt
print("同还原得到矩阵是否与原始矩阵相同：",np.allclose(A,B))

同还原得到矩阵是否与原始矩阵相同： True


 #### 基于SVD的维度压缩
 在进行压缩时，首先计算得到原始矩阵A（可以代表图片等），的对应$ U V_T\Sigma$矩阵，从中抽取信息量载荷大的k行，再还原新的矩阵 $A_,$ 对比原有矩阵$ A $得到压缩。

In [33]:
k=2
print("k值",k)
Sigma_k=Sigma[:k,:k]##奇异值矩阵选取k行ke列
print("奇异值矩阵选取k行k列:",Sigma_k)
U_k=U[:,:k]
print("右奇异矩阵选取k行",U_k)
Vt_k=Vt[:k,:]
print("左奇异矩阵选取列",Vt_k)

A_k=U_k@Sigma_k@Vt_k
print("通过计算得到压缩矩阵: \n",A_k)
print("原始矩阵 \n",A)


k值 2
奇异值矩阵选取k行k列: [[18.53581747  0.        ]
 [ 0.          5.0056557 ]]
右奇异矩阵选取k行 [[-0.55572489  0.40548161]
 [-0.59283199 -0.80531618]
 [-0.58285511  0.43249337]]
左奇异矩阵选取列 [[-0.18828164 -0.37055755 -0.74981208 -0.46504304 -0.22080294]
 [ 0.01844501  0.76254787 -0.4369731   0.27450785 -0.38971845]]
通过计算得到压缩矩阵: 
 [[ 1.97689227  5.36478923  6.83675076  5.3474913   1.48343826]
 [ 1.99460216  0.99798435 10.00090204  4.00360545  3.99732875]
 [ 2.07406947  5.6542408   7.15473299  5.61846914  1.54178136]]
原始矩阵 
 [[ 1  5  7  6  1]
 [ 2  1 10  4  4]
 [ 3  6  7  5  2]]


#### 实现图片压缩
https://blog.csdn.net/discoverer100/article/details/89356513

In [36]:
!pip install pillow

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple

You should consider upgrading via the 'C:\Users\tomis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.



     ---------------------------------------- 3.3/3.3 MB 165.0 kB/s eta 0:00:00


In [5]:
!pip install -U matplotlib

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ------------------------                 4.5/7.2 MB 41.2 kB/s eta 0:01:07


ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\socket.py", line 705, in read

In [6]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
def image_svd(A,k):
    U,s,Vt=np.linalg.svd(A)
    Sigma=np.zeros(A.shape)
    for i in range(len(s)):#为奇异值矩阵对角元素赋值
      Sigma[i,i]=s[i]
    U_k=

if __name__=="__main__":
    image=Image.open("forest.jpg","r")
    A=np.array(image)
    print("图片向量化: \n",A,"\n 图片形状：")
  

 
    
    

SyntaxError: invalid syntax (684456541.py, line 9)

In [ ]:
p