## SVD (Singular Value Decomposition）奇异值分解
https://zhuanlan.zhihu.com/p/29846048
> 优点：简化数据，去除噪声，提高算法的结果
> 
> 缺点：数据的转换可能难以理解
> 
> 适用数据范围：数值型数据
利用SVD实现，可以能够用小的多的数据来表示原始数据，如此，实际上是去除了噪声和多余信息。
---
结合特征分解知识

特征值的分解使用于

SVD是将任意复杂（注意对比特征分解只能适用于方阵）的矩阵用更小，更简单的3个矩阵的相乘表示，用这3个小矩阵来描述大矩阵的重要特征。

利用SVD 可以从稀疏矩阵（矩阵中有大量元素值为0）中提取有价值的信息，减少计算量，在使用线性代数的地方，基本上都要使用SVD。

SVD不但应用在PCA、图像压缩、数字水印、推荐系统和文章分类、LSA中，是很多机器学习算法基石。
### SVD数学定义
与特征值分解不同，SVD不要求原始矩阵为方阵。

$$ A=U_{m \times m} \Sigma_{m \times n} V^T_{n \times n}$$
-------
 A 为$m \times n$矩阵，$A \times A^T$ 将得到一个对称矩阵，即$A_{ij}=A_{ji}$
*  $U$ 是一个$m \times m$的矩阵，
*  $ \Sigma$ 是一个 $m \times n$ 的矩阵，除了主对角线上的元素以外全为0，主对角线上的每个元素都称为奇异值。奇异值矩阵是一个对角矩阵，除了对角元素外其他元素都为0
*  $V$ 是一个 $n \times n$ 的矩阵。
*  
$U$和$V$ 都是酉矩阵，即满足
$U^T U=E_{m \times m} , V^TV=E_{n \times n}$

>SVD是对数据进行有效特征整理的过程。首先，对于一个m×n矩阵A，我们可以理解为其有m个数据，n个特征，（想象成一个n个特征组成的坐标系中的m个点），然而一般情况下，这n个特征并不是正交的，也就是说这n个特征并不能归纳这个数据集的特征。SVD的作用就相当于是一个坐标系变换的过程，从一个不标准的n维坐标系，转换为一个标准的k维坐标系，并且使这个数据集中的点，到这个新坐标系的欧式距离为最小值（也就是这些点在这个新坐标系中的投影方差最大化），其实就是一个最小二乘的过程。进一步，如何使数据在新坐标系中的投影最大化呢，那么我们就需要让这个新坐标系中的基尽可能的不相关，我们可以用协方差来衡量这种相关性。A^T·A中计算的便是n×n的协方差矩阵，每一个值代表着原来的n个特征之间的相关性。当对这个协方差矩阵进行特征分解之后，我们可以得到奇异值和右奇异矩阵，而这个右奇异矩阵则是一个新的坐标系，奇异值则对应这个新坐标系中每个基对于整体数据的影响大小，我们这时便可以提取奇异值最大的k个基，作为新的坐标，这便是PCA的原理。

通过python中np.linga.svd 求奇异分解
 Python中svd后得到的sigma是一个行向量，Python中为了节省空间只保留了A的奇异值，所以我们需要将它还原为奇异值矩阵。同时需要注意的是，比如一个5*5 大小的矩阵的奇异值只有两个，但是他的奇异值矩阵应该是 5*5的，所以后面的我们需要手动补零，并不能直接使用diag将sigma对角化。
————————————————

https://blog.csdn.net/Cheese_pop/article/details/78346662

#笔记

<img src="https://s1.imagehub.cc/images/2022/09/02/_05.md.png" align="left"/>
<img src="https://s1.imagehub.cc/images/2022/09/02/_06.md.png" align="center"/>
<img src="https://s1.imagehub.cc/images/2022/09/02/_07.md.png" align="right"/>

利用svd定义求解$U \Sigma V$这三个矩阵

1. 首先求出$AA^T$矩阵
2. 根据$AA^T=U(\Sigma)^2U^T$这一个特征值分解，求出$U, \Sigma$
3. 根据特征值对 $\Sigma$中$\sigma_i$以及对应$U$中特征向量进行排序

In [ ]:
import numpy as np 
A=np.array([[1,5,7,6,1],[2,1,10,4,4],[3,6,7,5,2]])
print("待分解矩阵：\n",A)
print("求A与其转置内积：")
AAt=A@A.T 
print(AAt)
print("实现对A的特征值分解")
eig,eigv=np.linalg.eig(AAt)
print("求得特征值:",eig)
print("特征向量构成矩阵，即U: \n",eigv)
sigma=np.sqrt(np.diag(eig))
 
print("求得奇异值对角矩阵：\n",sigma)

print("根据特征值对 $\Sigma$中$\sigma_i$以及对应$U$中特征向量进行排序")

<img src="https://s1.imagehub.cc/images/2022/09/02/_08.md.png" align="left"/>
<img src="https://s1.imagehub.cc/images/2022/09/02/_09.md.png" align="center"/>
<img src="https://s1.imagehub.cc/images/2022/09/02/_10.md.png" align="right"/>
<img src="https://s1.imagehub.cc/images/2022/09/02/_11.md.png" align="left"/>
<img src="https://s1.imagehub.cc/images/2022/09/02/_12.md.png" align="center"/>
 

在求得$U \Sigma V$三个矩阵的基础上利用左、右奇异矩阵降维、奇异值矩阵对原矩阵进行降维
包括
1. 行压缩数据降维、列压缩数据降维
结合笔记，行压缩数据降维简单理解：
* 行压缩数据降维，列压缩数据降维分别**独立** 降维
* 行压缩降维 $A^{'}=U^T \times A$ 意味着$A$矩阵通过$U^T$所构成的标准正交空间变换，得到相互不线性相关的向量组合$A^{'}$，

由于$A^{'}$中各向量不线性相关就可以根据对应的奇异向量k值，选择信息量大的k行，
2. 对矩阵进行整体降维

In [4]:
import numpy as np 
A=np.array([[0,0,0,2,2],[0,0,0,3,3],[0,0,0,1,1],[1,1,1,0,0],[2,2,2,0,0],[5,5,5,0,0],[1,1,1,0,0]])
U,sigma,Vt=np.linalg.svd(A)
print("原矩阵A大小:",A.shape)
print("左奇异矩阵大小: \n",U.shape)
print("右奇异矩阵大小：\n",Vt.shape)
print("奇异值：\n",sigma)
print("观察奇异值，得到前两个奇异值远大于后面其他奇异值，故选择k=2")
print("截取U左奇异矩阵前两列：")
U2_t=U.T[:2,:]

print("U转置后选取奇异值最大的的k行:",U2_t.shape)
A_col_2=np.dot(U2_t,A)#U2_t@A
print("通过U_t(k) 与A进行内积，实现对A的列行的方向的压缩 \n",A_col_2)
print("行压缩数据降维后，A的大小",A_col_2.shape)
Vt2=Vt[:2,:]#选取奇异值最大两个对应的V转置后两行向量 
A_row_de=Vt2@A.T
print(A_row_de.T)
print("列压缩数据降维后，A的大小",A_row_de.T.shape)

原矩阵A大小: (7, 5)
左奇异矩阵大小: 
 (7, 7)
右奇异矩阵大小：
 (5, 5)
奇异值：
 [9.64365076e+00 5.29150262e+00 6.49628424e-16 1.43063514e-16
 2.79192092e-17]
观察奇异值，得到前两个奇异值远大于后面其他奇异值，故选择k=2
截取U左奇异矩阵前两列：
U转置后选取奇异值最大的的k行: (2, 7)
通过U_t(k) 与A进行内积，实现对A的列行的方向的压缩 
 [[-5.56776436e+00 -5.56776436e+00 -5.56776436e+00  1.66777673e-16
   1.66777673e-16]
 [ 2.16930682e-16  2.16930682e-16  2.16930682e-16 -3.74165739e+00
  -3.74165739e+00]]
行压缩数据降维后，A的大小 (2, 5)
[[ 0.00000000e+00 -2.82842712e+00]
 [ 0.00000000e+00 -4.24264069e+00]
 [ 0.00000000e+00 -1.41421356e+00]
 [-1.73205081e+00  1.23259516e-32]
 [-3.46410162e+00  2.46519033e-32]
 [-8.66025404e+00  4.93038066e-32]
 [-1.73205081e+00  1.23259516e-32]]
列压缩数据降维后，A的大小 (7, 2)


In [20]:
# 整体压缩
# 选取前k个U(i)*sigma(i)*Vt(i) 计算后相加，得到压缩后的A矩阵
print(A)
U,sigma,Vt=np.linalg.svd(A)
u1=np.mat(U[:,0])
print(type(u1))
vt1=np.mat(Vt[0,:])
 
sigma1=sigma[0]
a1=sigma1*u1.T@vt1
print(a1.shape)
u2=np.mat(U[:,1])
 
vt1=np.mat(Vt[1,:])
 
sigma2=sigma[1]
a2=sigma2*u1.T@vt1
print(a2.shape)
a12=a1+a2
print(a12)
 

[[0 0 0 2 2]
 [0 0 0 3 3]
 [0 0 0 1 1]
 [1 1 1 0 0]
 [2 2 2 0 0]
 [5 5 5 0 0]
 [1 1 1 0 0]]
<class 'numpy.matrix'>
(7, 5)
(7, 5)
[[-4.64289391e-16 -4.64289391e-16 -4.64289391e-16 -3.12012455e-16
  -3.12012455e-16]
 [ 2.93927860e-32  2.93927860e-32  2.93927860e-32  1.97525843e-32
   1.97525843e-32]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  6.72021505e-01
   6.72021505e-01]
 [ 2.00000000e+00  2.00000000e+00  2.00000000e+00  1.34404301e+00
   1.34404301e+00]
 [ 5.00000000e+00  5.00000000e+00  5.00000000e+00  3.36010753e+00
   3.36010753e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  6.72021505e-01
   6.72021505e-01]]


## SVD 应用1 推荐
步骤：
1. 数据加载
2. 定义相似度计算方法
3. 对信息进行降维
> 由于需要保留菜品信息（列），故采用左奇异矩阵相乘实现原矩阵行降维 
  $A_{'}=\Sigma*(U^T)_k \dot A$
4. 通过评分估计编写推荐算法
    对$m$用户
   1. $m_x$为未吃过菜品
   2. $m_i,m_j$分别代表m对$i,j$菜品打分
   3. $sim_{xi},sim_{xj}$为整体$x,i,j$菜品的相似度
   4. $m_x= \frac{m_i\times sim(xi)+m_j \times sim(xj)}{ sim(xi)+sim(xj)}$
   5. $x=1,2,3...n$代表$m$用户所有没有吃过菜，并计算得到对应$m_x$菜品推断得分。
   6. 找到推荐得分最高菜品，推荐给$m$用户

In [36]:
from inspect import Parameter
from re import S
import numpy as np 
from sklearn.metrics.pairwise import cosine_similarity
def ecludSim(x:np.ndarray,y:np.ndarray)->np.ndarray:
    '''欧氏距离
    
    Paramters:
    x: 计算相似度向量
    y: 计算相似度向量
    
    Returns:相似杜结果
    
    '''
    sim=np.linalg.norm(x,y)
    sim_norm=1/(1-sim)
    return sim_norm 
def pearSim(x:np.ndarray,y:np.ndarray)->np.ndarray:
    '''皮尔逊相关系数
    sim=np.corrcoef(x,y)
    '''
def cosSim(x:np.ndarray,y:np.ndarray)->np.ndarray:
    sim=float(x.T@y)/(np.linalg.norm(x)*np.linalg.norm(y))
    sim_norm=0.5+0.5*sim
    return sim_norm 

def sigmaPct(sigma,percentage):
    n=len(sigma)
    sum_n=np.sum(np.square(sigma))
    k=0
    sum_i=0
    for i in range(n):
        sum_i=sum_i+np.square(sigma[i]) 
        k=k+1
        if (float(sum_i)/float(sum_n))>=percentage:
            print(sum_i)
            print(sigma[:k])
            return k
            break
def simScore(data):
    len=socretable.shape[1]#菜品打分矩阵列数
    sims=[]
    for i in range(len):
        if i+1<len:
            sim=cosSim(data[:,i],data[:,i+1])
            sims.append(sim)
        else:
            break
    return sims
    
def estScore(socretable,userIndex=0):
    ''' 推荐菜品计算，输入为没有压缩过的矩阵
    Parameter:
        scoreData:输入计算矩阵
        userIndex:推荐用户id
        itemIndex:菜品id
    '''    
    itemLen=socretable.shape[1]#菜品打分矩阵列数
 
 
    score_dic={}
    #计算菜品之间的相关系数
    sims=0.5+0.5*cosine_similarity(socretable.T)# 菜品相似矩阵计算（基于cos）
    score=[]
    #得到哪些菜itemindex用户没有吃过
    score_m=socretable[userIndex,:].flatten()
    print("用户:{},对应打分向量:{},形状{}".format(userIndex,score_m,score_m.shape))
    for i in range( itemLen):
       if score_m[:,i]==0:
           simx=sims[i,:]#x菜品与其他菜品（包括自己）的相关性
           print("菜品{}与其他菜品相关度{},对应向量形状{}".format(i,simx,simx.shape))
           score_x=np.sum(score_m@simx)/np.sum(score_m)
           score.append( score_x)
           score_dic[i]=score_x
    return score_dic
            
def estScoreSVC(scoreData,scoreSVC,userIndex=0):
    ''' 计算菜品itemIndex 
    Parameters:
        scoreData:降维前矩阵
        scoreSVC: 将维后矩阵
        userIndex:推荐用户id
        itemIndex:菜品id
    Returns:
        返回字典，key为菜的index，value为推荐打分
    '''    
    itemLen=scoreSVC.shape[1]#菜品打分矩阵列数,代表菜数目
 
 
    score_dic={}
    #计算菜品之间的相关系数
    sims=0.5+0.5*cosine_similarity(scoreSVC.T)# 菜品相似矩阵计算（基于cos）
     
    
    score_m=scoreData[userIndex,:].flatten()#得到哪些菜itemindex用户没有吃过
    print("用户:{},对应打分向量:{},形状{}".format(userIndex,score_m,score_m.shape))
    for i in range( itemLen):
       if score_m[:,i]==0:
           simx=sims[i,:]#x菜品与其他菜品（包括自己）的相关性
           print("菜品{}与其他菜品相关度{},对应向量形状{}".format(i,simx,simx.shape))
           score_x=np.sum(score_m@simx)/np.sum(simx)
            
           score_dic[i]=score_x
    return score_dic        
    
    
if __name__=='__main__':
    #U,sigma,Vt=np.linalg.svd(data)
    #左奇异行向量降维
    #k=sigmaPct(sigma,0.8)
    print("测试相似度计算")
    socretable=np.mat([[5,1,4],[1,5,2],[5,2,4],[4,1,4]])
    print(socretable)
    sim1=cosSim(socretable[:,0],socretable[:,1])
    print(sim1)
    scoreData = np.mat([
    [5,2,1,4,0,0,2,4,0,0,0],
    [0,0,0,0,0,0,0,0,0,3,0],
    [1,0,5,2,0,0,3,0,3,0,1],
    [0,5,0,0,4,0,1,0,0,0,0],
    [0,0,0,0,0,4,0,0,0,4,0],
    [0,0,1,0,0,0,1,0,0,5,0],
    [5,0,2,4,2,1,0,3,0,1,0],
    [0,4,0,0,5,4,0,0,0,0,5],
    [0,0,0,0,0,0,4,0,4,5,0],
    [0,0,0,4,0,0,1,5,0,0,0],
    [0,0,0,0,4,5,0,0,0,0,3],
    [4,2,1,4,0,0,2,4,0,0,0],
    [0,1,4,1,2,1,5,0,5,0,0],
    [0,0,0,0,0,4,0,0,0,4,0],
    [2,5,0,0,4,0,0,0,0,0,0],
    [5,0,0,0,0,0,0,4,2,0,0],
    [0,2,4,0,4,3,4,0,0,0,0],
    [0,3,5,1,0,0,4,1,0,0,0]
    ])
    print(scoreData.shape)
    U,sigma,Vt=np.linalg.svd(scoreData)
    print(U.shape,sigma.shape,Vt.shape)
    k=sigmaPct(sigma,0.9)
    print("满足信息量保留:{},的奇异值数目为:{}".format(0.9,k))
    print("通过左奇异矩阵对原矩阵进行转换，实现行的降维 \n")
    sigma_k=np.eye(6)*sigma[:6]
    print(sigma_k)
    scoreData_r=sigma_k*U.T[:6,:]@scoreData
    print("行降维后的评分矩阵大小:",scoreData_r.shape)

    sims=0.5+0.5*cosine_similarity(scoreData.T)
    print(sims[:,2])
    score_x=estScore(scoreData,17)
    print("矩阵压缩前，进行推荐计算，第17号顾客没有吃过的菜中：",score_x)
    score_x2=estScoreSVC(scoreData,scoreData_r,17)
    print("矩阵压缩后，进行推荐计算，第17号顾客没有吃过的菜中：",score_x2)
 
 

测试相似度计算
[[5 1 4]
 [1 5 2]
 [5 2 4]
 [4 1 4]]
0.7633073594246896
(18, 11)
(18, 18) (11,) (11, 11)
823.0038413383999
[18.00984878 13.34523472 11.52884033 10.1161419   7.13556169  5.86405759]
满足信息量保留:0.9,的奇异值数目为:6
通过左奇异矩阵对原矩阵进行转换，实现行的降维 

[[18.00984878  0.          0.          0.          0.          0.        ]
 [ 0.         13.34523472  0.          0.          0.          0.        ]
 [ 0.          0.         11.52884033  0.          0.          0.        ]
 [ 0.          0.          0.         10.1161419   0.          0.        ]
 [ 0.          0.          0.          0.          7.13556169  0.        ]
 [ 0.          0.          0.          0.          0.          5.86405759]]
行降维后的评分矩阵大小: (6, 11)
[0.6298227  0.67514404 1.         0.72171446 0.65067707 0.60408973
 0.91768331 0.61053239 0.75243302 0.53867935 0.54479309]
用户:17,对应打分向量:[[0 3 5 1 0 0 4 1 0 0 0]],形状(1, 11)
菜品0与其他菜品相关度[1.         0.65231795 0.6298227  0.85376378 0.5932655  0.52783971
 0.61112511 0.89769826 0.59027778 0.52660

c:\Users\tomis\.conda\envs\luck\lib\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
c:\Users\tomis\.conda\envs\luck\lib\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
c:\Users\tomis\.conda\envs\luck\lib\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [34]:
import numpy as np

scoreData = np.mat([
[5,2,1,4,0,0,2,4,0,0,0],
[0,0,0,0,0,0,0,0,0,3,0],
[1,0,5,2,0,0,3,0,3,0,1],
[0,5,0,0,4,0,1,0,0,0,0],
[0,0,0,0,0,4,0,0,0,4,0],
[0,0,1,0,0,0,1,0,0,5,0],
[5,0,2,4,2,1,0,3,0,1,0],
[0,4,0,0,5,4,0,0,0,0,5],
[0,0,0,0,0,0,4,0,4,5,0],
[0,0,0,4,0,0,1,5,0,0,0],
[0,0,0,0,4,5,0,0,0,0,3],
[4,2,1,4,0,0,2,4,0,0,0],
[0,1,4,1,2,1,5,0,5,0,0],
[0,0,0,0,0,4,0,0,0,4,0],
[2,5,0,0,4,0,0,0,0,0,0],
[5,0,0,0,0,0,0,4,2,0,0],
[0,2,4,0,4,3,4,0,0,0,0],
[0,3,5,1,0,0,4,1,0,0,0]
])

def cosSim(vec_1, vec_2):
    dotProd = float(np.dot(vec_1.T, vec_2))
    normProd = np.linalg.norm(vec_1)*np.linalg.norm(vec_2)
    return 0.5+0.5*(dotProd/normProd)

def estScore(scoreData,scoreDataRC,userIndex,itemIndex):
    n = np.shape(scoreData)[1]
    simSum = 0
    simSumScore = 0
    for i in range(n):
        userScore = scoreData[userIndex,i]
        if userScore == 0 or i == itemIndex:
            continue
        sim = cosSim(scoreDataRC[:, i], scoreDataRC[:, itemIndex])
        simSum = float(simSum + sim)
        simSumScore = simSumScore + userScore * sim
    if simSum == 0:
        return 0
    return simSumScore / simSum

U, sigma, VT = np.linalg.svd(scoreData)

sigmaSum = 0
k_num = 0

for k in range(len(sigma)):
    sigmaSum = sigmaSum + sigma[k] * sigma[k]
    if float(sigmaSum)/float(np.sum(sigma ** 2)) > 0.9:
        k_num = k+1
        break

sigma_K = np.mat(np.eye(k_num)*sigma[:k_num])
scoreDataRC = sigma_K * U.T[:k_num, :] * scoreData

n = np.shape(scoreData)[1]
userIndex = 17

for i in range(n):
    userScore = scoreData[17, i]
    if userScore != 0:
        continue
    print("index:{},score:{}".format(i, estScore(scoreData, scoreDataRC, userIndex, i)))

index:0,score:2.6347116715331165
index:4,score:2.9259893459771127
index:5,score:2.9337238848085887
index:8,score:2.965707317848275
index:9,score:2.9057073432965526
index:10,score:2.926348465526288
