# 线性代数应用

## 前言：
线性代数在工程领域、经济学、人工智能中都有广泛的应用。本课程由浅入深介绍各领域中的应用，并附加习题。

内容包括

1.食品营养
经济学
2.管理学
3.图像处理
4.数据处理

## 0.营养学方程构建

剑桥减肥食谱
80年代Howard博士领导的科学家团队，经过8年的对过度肥胖病人的临床研宄，在剑桥大学完成的．这种低热量的粉状食品精确地平衡了碳水化合物，高质量的蛋白质和脂肪，配合维
生素，矿物质，微量元素和电解质．数百万人应用这一食谱实现快速和有效的减肥．为得到希望的数量和比例的营养．How“d博士在食谱中加入了多种的食品．每种食品供应了多种所需要的成份，然而没有按正确
的比例．例如，脱脂牛奶是蛋白质的主要来源但包含过多的钙，因此大豆粉用来作为蛋白质的来源，它包含较少量的钙．然而，大豆粉包含过多的脂肪，因而加上乳清，因它含脂肪较少．然而乳清又含有过多的碳水化合物“·

我们来构建自己的健康食谱


以下是一个营养食品表，列对应不同的人体所需营养物质，行对应的是不同不同食品，行列元素为该食品每百g中含对应营养成分的量，最后一列为每天人体所需不同营养物质的总量。
求我们为了保持健康，每填各个食品的输入量是多少？


| 营养元素     | 牛奶         |大豆粉     | 乳糖        |每天所需量（克)|
| ----------- | ----------- |----------- | ----------- |----------- |
|蛋白质     | 36       |51|12|33|
| 碳水   |52        |34|74|45|
|脂肪   |0        |7|1.1|3|




In [10]:
import numpy as np
A=(np.array([[36,52,0],[51,34,7],[13,74,1.1]])).T
b=np.array([33,45,3]).T
print(A)
print(b)
np.linalg.solve(A,b)

[[36.  51.  13. ]
 [52.  34.  74. ]
 [ 0.   7.   1.1]]
[33 45  3]


array([0.27722318, 0.39192086, 0.23323088])

### 1.线性代数在经济学中的应用

--
参考：
数理经济学的基本方法

###1.1 差分方程-人口迁移
在经济管理学中，需要研究随着时间变化的动力学模型，这种系统通常在离散的时刻测量，得到一个向量序列$x_0,x_1,..x_n$向量$x_n$的各个元素对应该系统在第$n$次检测时候中的状态信息。

如果有矩阵 $A$ 使得$x_1=Ax_0, x_2=Ax_2$ 一般：$$x_k+1=Ax_k,k=0,1,2,...$$

称之为线性差分方程，（或递归关系）。

例如讨论城乡迁移问题，设2000年城市人口为$city_{2000} 农村人口为r_{2000}$,每一年有$p_1 城市人口留在城市，有q_1农村人口转移到城市$

首先2001年城市人口为:$$ city2001= \begin{bmatrix} p_1 \\ (1-p_1) \end{bmatrix} *city_{2000}$$ 
农村人口为：
$$ rural2001= \begin{bmatrix} q_1 \\ (1-q_1) \end{bmatrix} *rural_{2000}$$ 
得到2001人人口向量为$$ \begin{bmatrix} city_{2001} \\ rural_{2001} \end{bmatrix} = \begin{bmatrix} p_1 \\ (1-p_1) \end{bmatrix} *city_{2000} + \begin{bmatrix} q_1 \\ (1-q_1) \end{bmatrix} *rural_{2000} =\begin{bmatrix} p_1 && q_1 \\ (1-p_1) && (1-q_1) \end{bmatrix} * \begin{bmatrix} city_2000 \\ rural_2000 \end{bmatrix}$$
print("转换矩阵：",tran.T)
popu2001=tran.T.dot(popu2000)

其中
$$  \begin{bmatrix} p_1 && q_1 \\ (1-p_1) && (1-q_1) \end{bmatrix} $$所构成的矩阵$M$
则夏义年份的城乡人口向量可以通过以下公式得到：
$$ x_{n+1}=x_n*M$$


In [ ]:
习题2在某城市，每年大约有5%的城市人口迁移到农村，同时有3%的农村人口迁移到城市，设2000年时，该城市有城市人口6000，000人，农村人口4000，000人，求2002年该城乡人口分别多少人。


In [22]:
import numpy as np
city=600000
rural=400000aEDdD
print("2001年，城市人口转换情况,", city*city_tran)DdDS
tran=np.array([[0.95,0.05],[0.03,0.97]])
print("转换矩阵：",tran.T)
popu2001=tran.T.dot(popu2000)
print(popu2001)
popu2002=tran.T.dot(popu2001)
print(popu2002)


2000年城乡人口向量 [600000 400000]
2001年，城市人口转换情况, [570000.  30000.]
2001年，乡村人口转换情况, [ 12000. 388000.]
2001年，城乡人口向量： [582000. 418000.]
转换矩阵： [[0.95 0.03]
 [0.05 0.97]]
[582000. 418000.]
[565440. 434560.]


### 2. 基于线性方程计算投入产出模型

* 投入产出模型”国民经济各个部门之间存在着相互依存和制约关系，每个部门在运转中将其他部门的产品或半成品（称为投入）经过加工变为自己的产品（称为产出）
* 如果根据各部门间投入和产出的平衡关系，确定各邵门的产出水平以满足社会的需求是投入产出模型要研究的问题
* 投入产出是20世纪30年代由美国经济学家W．Leontief首先提出和研究的，几十年来在理论和实践方面得到很大发展·投入产出模型已经从静态扩展到动态，并且随着与数量经济分析方法的日益融合，其应用领域不断扩大，W.Leontief也因此获得了1973年诺贝尔经济学奖
---
投入出产出表
> 描述了国民经济各个部门之间的生成和消耗、投入和产出的数量关系。

例如：设某国的经济体系有n个部门（例如制造业、农业、服务业），这些服务部门生产商品和服务，我们以$x$代表各个部门产出的价值（统一价值单位，例如百万美元）。
$d$ 代表消费者需求，在此消费者只消费不生产。构成了最终消费向量。

但生产部门在生产过程中也必须消耗其他部门的投入（例如工业消耗农业初级产品，农业消耗农业机械等），也就是说，生产制本身也有**中间需求**。
投入产出模型就是考虑在理想状态下，存在某一生产向量，正好满足了中间需求与最终需求：
$$[最终产出向量x]=[中间需求A]+[最终需求d]$$

例如：
表1 每单位产出消费投入
| 消耗来着   | 工业 $c_1$        |农业 $c_2$     | 服务业 $c_3$        | 
| ----------- | ----------- |----------- | ----------- | 
|工业    | 0.5       |0.4|0.2| 
| 农业   |0.2        |0.3|0.1| 
|服务业  |0.1        |0.1|0.3| 
在此，我们如果想生产100个单位的服务业产品，那么将消耗多少？

$$100c_1=100 * \begin{bmatrix} 0.2 \\ 0.1\\0.3 \end{bmatrix}= \begin{bmatrix}20 \\ 10 \\30 \end{bmatrix}$$
得到消耗20+10+30=70个单位
最终得到三个部门的中间需求为
$${中间需求}=x_1c_1+x_2c_2+x_3c_3=CX$$
其中 $C$ 为消耗矩阵 $[c_1,c_2,...,c_n]$



 

以上模型的基本假设是，对每个部门有一个单位消费向量，他列出
* 列氏投入产出模型
$$ x(总产出)=Cx(中间需求）+d(最终需求)$$
 下面我们做一些变换:
1. $x$向量乘单位矩阵$I$并进行等式变换得到
$$Ix-Cx=d -> (I-C)x=d$$
$$x=(I-C)^{-1}d$$
就可以用过纠结以上的方程得到总产出向量
 

习题：结合表1，设最终的需求是工业50但，农业30单位，服务业20单位，求总生产水平$x$

In [3]:
import numpy as np 
C=np.array([[0.5,0.4,0.2],[0.2,0.3,0.1],[0.1,0.1,0.3]])
print(C)
b=np.array([50,30,20]).T
I=np.eye(3) 
x=np.linalg.solve((I-C),b)
print("为生产最终需求[50,30,20],需要消耗对应产业分别为：",np.round(x))

[[0.5 0.4 0.2]
 [0.2 0.3 0.1]
 [0.1 0.1 0.3]]
为生产最终需求[50,30,20],需要消耗对应产业分别为： [226. 119.  78.]


### 3.层次分析-python实现
>层次分析
>层次构分析理论(AHP〕是将评价对象或河题机为一个系统，根据问题的的性质和要达到的总目标，将问题分解成不同的组成要素，并按照因素间的相互关联度及隶
属关系，将因素按不河层次集组合，从而形成一个多层次的分析构系统，把问题过条理化、层次化：
可以说层次分析法是一种定性与定量完美结合的半定量方法，其对应了人类的辩证思维过程，将一个复杂的问题层次分解，同一层的各个元素具有大致相等的地位，不同层的元素具有某种联系；再对单层的元数构造判读矩阵以得出层次单排序,并进行一致性检验；最后，为了计算层次总排序，采用逐层叠加方法，从最高层开始，由高到第逐层计算，推算出所有层次对最高层次的总排序zhi
 